Script started on 2018-08-21 10:41:57-05:00
]0;mcather@matthew-pc:~/projects/comp-3500[01;32m[mcather@matthew-pc[01;37m comp-3500[01;32m]$[00m gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 8.2.0 (GCC) 
]0;mcather@matthew-pc:~/projects/comp-3500[01;32m[mcather@matthew-pc[01;37m comp-3500[01;32m]$[00m gcc -g -lm -o simple simple.c 
]0;mcather@matthew-pc:~/projects/comp-3500[01;32m[mcather@matthew-pc[01;37m comp-3500[01;32m]$[00m man ldd
[?1049h[22;0;0t[?1h=LDD(1)                     Linux Programmer's Manual                    LDD(1)[m
[m
[1mNAME[0m[m
       ldd - print shared object dependencies[m
[m
[1mSYNOPSIS[0m[m
       [1mldd[0m [[4moption[24m]... [4mfile[24m...[m
[m
[1mDESCRIPTION[0m[m
       [1mldd[0m  prints the shared objects (shared libraries) required by each pro‐[m
       gram or shared object specified on the command line.  An example of its[m
       use and output is the following:[m
[m
         $ [1mldd[0m [1m/bin/ls[0m[m
                 linux-vdso.so.1 (0x00007ffcc3563000)[m
                 libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f87e5459000)[m
                 libcap.so.2 => /lib64/libcap.so.2 (0x00007f87e5254000)[m
                 libc.so.6 => /lib64/libc.so.6 (0x00007f87e4e92000)[m
                 libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f87e4c22000)[m
                 libdl.so.2 => /lib64/libdl.so.2 (0x00007f87e4a1e000)[m
                 /lib64/ld-linux-x86-64.so.2 (0x00005574bf12e000)[m
                 libattr.so.1 => /lib64/libattr.so.1 (0x00007f87e4817000)[m
                 libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f87e45fa000)[m
[7m Manual page ldd(1) line 1 (press h for help or q to quit)[27m[K[K[?1l>[?1049l[23;0;0t]0;mcather@matthew-pc:~/projects/comp-3500[01;32m[mcather@matthew-pc[01;37m comp-3500[01;32m]$[00m ldd simple
	linux-vdso.so.1 (0x00007fffa11c8000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f9a61872000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f9a616ae000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f9a61a2f000)
]0;mcather@matthew-pc:~/projects/comp-3500[01;32m[mcather@matthew-pc[01;37m comp-3500[01;32m]$[00m vim[K[K[Knvim sim[K[K[K.gdbinit 
[?1049h[22;0;0t[?1h=[H[2J[?2004h[8;24;80t[r[1;1H[H[2J[?25h[?25l[2 q[2 q[H[2J[?25h[?25l(B[m[38;5;130mfile[C(B[msimple
[38;5;130mbreak[C(B[mmain
[38;5;130mbreak[C(B[msqrt
[38;5;130minfo[C(B[m[32mregisters
(B[m[94m~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
(B[0;1;7m.gdbinit                                                      1,1            All[H[?25h[?25l[?1004h[?25h[?25l[24;70H(B[m:[H[?25h[?25l[24;70H[K[24;1H:[2 q[?25h[?25lq[?25h[?25l[24;1H[?25h[?25l[2 q[2 q(B[m[?25h[?1l>[?1049l[23;0;0t[?2004l[?1004l[?25h]0;mcather@matthew-pc:~/projects/comp-3500[01;32m[mcather@matthew-pc[01;37m comp-3500[01;32m]$[00m gdb simple[K[K[K[K[K[K[K[K[K[K./simple 
The average is 22.468278
]0;mcather@matthew-pc:~/projects/comp-3500[01;32m[mcather@matthew-pc[01;37m comp-3500[01;32m]$[00m gdb simple
bash: gdb: command not found
]0;mcather@matthew-pc:~/projects/comp-3500[01;32m[mcather@matthew-pc[01;37m comp-3500[01;32m]$[00m exit
exit

Script done on 2018-08-21 10:43:16-05:00

Script started on 2018-08-21 10:50:41-05:00
]0;mcather@matthew-pc:~/projects/comp-3500[01;32m[mcather@matthew-pc[01;37m comp-3500[01;32m]$[00m gdb
GNU gdb (GDB) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Breakpoint 1 at 0x1161: file simple.c, line 4.
Breakpoint 2 at 0x1050
.gdbinit:4: Error in sourced command file:
The program has no registers now.
(gdb) r
Starting program: /home/mcather/projects/comp-3500/simple 

Breakpoint 1, main () at simple.c:4
4	int main() {
(gdb) n
5		int A[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
(gdb) s
7		size_t length = sizeof(A) / sizeof(A[0]);
(gdb) c
Continuing.

Breakpoint 2, 0x00007ffff7e26370 in sqrtf64 () from /usr/lib/libm.so.6
(gdb) q
A debugging session is active.

	Inferior 1 [process 13157] will be killed.

Quit anyway? (y or n) y
]0;mcather@matthew-pc:~/projects/comp-3500[01;32m[mcather@matthew-pc[01;37m comp-3500[01;32m]$[00m exit
exit

Script done on 2018-08-21 10:50:57-05:00
